name: Build and deploy
on: 
    push:
        branches: main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ vars.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          -
            name: Build and push
            uses: docker/build-push-action@v6
            with:
              context: .
              push: true
              tags: |
               ${{ vars.DOCKERHUB_USERNAME }}/helloworld:${{github.sha}}
               ${{ vars.DOCKERHUB_USERNAME }}/helloworld:latest
          - run:
               docker run -d -e GITHUB_TOKEN=${{vars.GITHUB_TOKEN}} -name -p 5001:50001 ${{ vars.DOCKERHUB_USERNAME }}/helloworld:${{github.sha}}
          - run: docker ps | grep "${{ vars.DOCKERHUB_USERNAME }}/helloworld:${{github.sha}}"" 
          - name: Checki if container is up and running
            run: curl localhost:5001/healthz
          - run: docker kill $(docker ps | grep "${{ vars.DOCKERHUB_USERNAME }}/helloworld:${{github.sha}}" | cut -d" " -f1)
          - run: docker rm hello
